# generated by datamodel-codegen:
#   filename:  universal_course.json
#   timestamp: 2025-06-15T00:01:44+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, EmailStr, Field


class CourseStatus(Enum):
    Active = 'Active'
    Inactive = 'Inactive'
    New = 'New'
    Retired = 'Retired'
    Pending_Review = 'Pending Review'
    Cancelled = 'Cancelled'
    Closed = 'Closed'


class Department(BaseModel):
    deptId: str = Field(..., description='System-generated unique ID.')
    code: Optional[str] = Field(None, description="School-local dept code (e.g. 'CS').")
    name: str = Field(..., description='Full dept/faculty name.')
    parentId: Optional[str] = Field(None, description='deptId of parent unit, if any.')


class Season(Enum):
    Winter = 'Winter'
    Spring = 'Spring'
    Summer = 'Summer'
    Fall = 'Fall'


class Term(BaseModel):
    termId: str = Field(..., description="Canonical ID, e.g. '2025FA'.")
    year: int = Field(..., description='Calendar year, e.g. 2025.')
    season: Season = Field(..., description='Season name.')
    startDate: Optional[date] = Field(None, description='Term start date.')
    endDate: Optional[date] = Field(None, description='Term end date.')


class Instructor(BaseModel):
    instructorId: str = Field(..., description='System-generated unique ID.')
    name: str = Field(..., description='Full name.')
    email: EmailStr = Field(..., description='Contact email.')
    role: Optional[str] = Field(
        None, description="Teaching role (e.g. 'Lecturer','TA')."
    )
    departmentId: Optional[str] = Field(None, description='deptId of home department.')


class Type(Enum):
    Lecture = 'Lecture'
    Lab = 'Lab'
    Tutorial = 'Tutorial'
    Exam = 'Exam'
    Other = 'Other'
    Seminar = 'Seminar'


class DayOfWeekEnum(Enum):
    Mon = 'Mon'
    Tue = 'Tue'
    Wed = 'Wed'
    Thu = 'Thu'
    Fri = 'Fri'
    Sat = 'Sat'
    Sun = 'Sun'


class Meeting(BaseModel):
    type: Type = Field(..., description='Block type.')
    dayOfWeek: Optional[List[DayOfWeekEnum]] = Field(None, description='Days of week.')
    startTime: Optional[str] = Field(None, pattern='^([01]\\d|2[0-3]):([0-5]\\d)$')
    endTime: Optional[str] = Field(None, pattern='^([01]\\d|2[0-3]):([0-5]\\d)$')
    startDate: Optional[date] = None
    endDate: Optional[date] = None
    location: Optional[str] = None
    raw: Optional[str] = Field(None, description='Original raw schedule text.')


class Delivery(Enum):
    InPerson = 'InPerson'
    Online = 'Online'
    Hybrid = 'Hybrid'
    Distance = 'Distance'


class Section(BaseModel):
    sectionId: str
    courseCode: str
    termId: str
    sectionCode: Optional[str] = None
    status: Optional[str] = None
    capacity: Optional[int] = Field(None, ge=0)
    enrolled: Optional[int] = Field(None, ge=0)
    waitlist: Optional[int] = Field(None, ge=0)
    delivery: Optional[Delivery] = None
    instructors: Optional[List[Instructor]] = None
    meetings: Optional[List[Meeting]] = None
    raw: Optional[Dict[str, Any]] = Field(
        None, description='All raw source-section fields.'
    )


class Type1(Enum):
    AND = 'AND'
    OR = 'OR'
    COURSE = 'COURSE'
    N_OF = 'N_OF'
    CREDITS = 'CREDITS'
    PROGRAM_REGISTRATION = 'PROGRAM_REGISTRATION'
    SUBJECT_CREDITS_AT_LEVEL = 'SUBJECT_CREDITS_AT_LEVEL'
    MIN_AVERAGE = 'MIN_AVERAGE'
    MIN_GRADE = 'MIN_GRADE'
    HIGHSCHOOL_REQUIREMENT = 'HIGHSCHOOL_REQUIREMENT'
    MIN_EXPERIENCE = 'MIN_EXPERIENCE'
    PROGRESSION_STATUS = 'PROGRESSION_STATUS'
    PHASE_REQUIREMENT = 'PHASE_REQUIREMENT'
    RAW_UNPARSED = 'RAW_UNPARSED'
    EXCLUDE_COURSE = 'EXCLUDE_COURSE'
    SUBJECT_CREDITS = 'SUBJECT_CREDITS'
    EQUIVALENT = 'EQUIVALENT'


class RequisiteExpression(BaseModel):
    type: Type1 = Field(..., description='The type of requisite node.')
    expressions: Optional[List[RequisiteExpression]] = Field(
        None, description='Array of nested expressions for AND/OR logic.'
    )
    courses: Optional[List[str]] = Field(
        None,
        description='Array of course codes for COURSE, OR, N_OF, or EXCLUDE_COURSE types.',
    )
    course: Optional[str] = Field(
        None, description='The course code for a MIN_GRADE type.'
    )
    count: Optional[int] = Field(
        None, description='The number required for an N_OF type.', ge=1
    )
    credits: Optional[float] = Field(
        None,
        description='Number of credits for CREDITS, SUBJECT_CREDITS, or SUBJECT_CREDITS_AT_LEVEL types.',
        ge=0.0,
    )
    subject: Optional[str] = Field(
        None,
        description='The subject area for SUBJECT_CREDITS or SUBJECT_CREDITS_AT_LEVEL.',
    )
    level: Optional[int] = Field(
        None,
        description='The course level (e.g., 3000) for SUBJECT_CREDITS_AT_LEVEL.',
        ge=1000,
    )
    percentage: Optional[float] = Field(
        None,
        description='The minimum percentage for a MIN_AVERAGE or MIN_GRADE type.',
        ge=0.0,
        le=100.0,
    )
    program: Optional[str] = Field(
        None, description='The program name for a PROGRAM_REGISTRATION type.'
    )
    phase: Optional[int] = Field(
        None,
        description='The program phase number required (e.g., 1, 2) for a PHASE_REQUIREMENT type.',
        ge=1,
    )
    description: Optional[str] = Field(
        None,
        description='A textual description for HIGHSCHOOL_REQUIREMENT, MIN_EXPERIENCE, or PROGRESSION_STATUS types.',
    )
    value: Optional[str] = Field(
        None, description='The raw string value if the type is RAW_UNPARSED.'
    )


class Term1(Enum):
    Winter = 'Winter'
    Spring = 'Spring'
    Summer = 'Summer'
    Fall = 'Fall'


class Year(Enum):
    All = 'All'
    Even = 'Even'
    Odd = 'Odd'
    Annually = 'Annually'
    Biennially = 'Biennially'
    Triennially = 'Triennially'


class OfferingPattern(BaseModel):
    terms: Optional[List[Term1]] = None
    years: Optional[List[Year]] = None
    note: Optional[str] = None


class UniversalCourseSchema(BaseModel):
    courseId: str = Field(
        ..., description='A canonical, unique ID for the course across all systems.'
    )
    courseCode: str = Field(
        ..., description="The school-specific code (e.g., 'ACCT*1220', 'CS 101')."
    )
    title: str = Field(..., description='The official title of the course.')
    description: Optional[str] = Field(
        None, description='The comprehensive descriptive text for the course.'
    )
    department: Optional[Department] = Field(
        None, description='The primary academic department offering the course.'
    )
    level: Optional[int] = Field(
        None,
        description='The academic level of the course (e.g., 1000 for 1st year).',
        ge=0,
    )
    credits: float = Field(
        ..., description='The academic credit value of the course.', ge=0.0
    )
    prerequisites: Optional[Union[RequisiteExpression, str]] = Field(
        None, description='Structured expression for prerequisites, or a raw string.'
    )
    corequisites: Optional[Union[RequisiteExpression, str]] = Field(
        None, description='Structured expression for corequisites, or a raw string.'
    )
    antirequisites: Optional[List[str]] = Field(
        None, description='Courses that cannot be taken if this course is taken.'
    )
    crossListings: Optional[List[str]] = Field(
        None, description='Other course codes under which this course is also listed.'
    )
    tags: Optional[List[str]] = Field(
        None, description='Keywords for interest-based search or categorization.'
    )
    termsOffered: Optional[List[OfferingPattern]] = Field(
        None, description='General patterns of when the course is offered.'
    )
    courseStatus: Optional[CourseStatus] = None
    effectiveStartDate: Optional[date] = None
    effectiveEndDate: Optional[date] = None
    sections: Optional[List[Section]] = None
    extensions: Optional[Dict[str, Any]] = Field(
        None, description='Catch-all for school-specific or non-standard extras.'
    )
    raw: Optional[Dict[str, Any]] = Field(
        None,
        description='Top-level raw source fields, preserving original data if needed.',
    )


RequisiteExpression.model_rebuild()
